import { type ReactNode } from "react";

import { ThemeProvider } from "@/app/_components/theme-provider";
import "@/styles/globals.css";
import { TRPCReactProvider } from "@/trpc/react";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Time Machine Next",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
